Concatenate buffers manually instead of using Buffer.concat
The latter fails in iojs v3.0.0 with:

	TypeError: buf.copy is not a function
		at Function.Buffer.concat (buffer.js:208:9)
			at Readable.<anonymous>
	(/home/travis/build/resin-io/resin-request/lib/utils.coffee:127:33)
			at emitNone (events.js:67:13)
			at Readable.emit (events.js:166:7)
			at endReadableNT (_stream_readable.js:889:12)
			at doNTCallback2 (node.js:429:9)
			at process._tickDomainCallback (node.js:384:17)